---
version: "3.7"

services:
  client:
    build: ../client/
    ports:
      - "3000:3000"
    depends_on:
      - api
  api:
    build: ../api/
    ports:
      - "8080:8080"
    environment:
      - PASSWORD=FALKERKUL
      - MONGO_URL=mongodb://mongo:27017/abasjakk
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4
